"""Standalone 3-stage SQL verification (the Reviewer logic).

Extracted from ``workflow.graph.verification_node`` so both the LangGraph pipeline
and the multi-agent orchestrator run **identical** verification semantics, and so
the Reviewer can be imported without pulling in the heavy generator stack (this
module depends only on the lightweight verifier classes: sqlglot + stdlib).
"""

from typing import Optional

from loguru import logger

from aegis_types import SQL, VerificationResult, VerificationStatus
from verifier.grammar_verifier import GrammarVerifier
from verifier.schema_verifier import SchemaVerifier
from verifier.execution_verifier import ExecutionVerifier
from verifier.feedback_generator import FeedbackGenerator


def run_verification(
    sql: SQL,
    schema,
    db_path: Optional[str],
    vcfg=None,
    candidate_exec: Optional[dict] = None,
    generation_count: int = 1,
) -> VerificationResult:
    """Verify ``sql`` through grammar → schema → execution and return the result.

    Args:
        sql: the generated SQL (its ``.verified`` / ``.verification_result`` are set).
        schema: the full ``Schema`` (for the schema stage).
        db_path: SQLite path; execution is skipped for ``None`` / ``":memory:"``.
        vcfg: the ``verifier`` config sub-object (stage toggles, timeouts). May be None.
        candidate_exec: optional pre-computed execution diagnostics (from selection),
            reused instead of re-executing.
        generation_count: number of generations so far — bounds the empty-result
            soft-fail so an accepted final answer is never marked failed.
    """
    if not sql.text or sql.text.strip() == "":
        vr = VerificationResult(
            status=VerificationStatus.GRAMMAR_FAIL,
            grammar_valid=False, schema_valid=False, execution_valid=False,
            error_message="Empty SQL generated by model",
            structured_feedback=None, execution_result=None,
        )
        sql.verified = False
        sql.verification_result = vr
        return vr

    grammar_valid = schema_valid = execution_valid = True
    status = VerificationStatus.PASS
    error_message = None
    execution_result = None

    # --- Stage 1: Grammar (sqlglot parse) ---
    ast = None
    if vcfg is None or vcfg.grammar_check:
        try:
            gv = GrammarVerifier(dialect=sql.dialect or "sqlite")
            grammar_valid, error_message = gv.verify(sql)
            if grammar_valid:
                ast = gv.parse_to_ast(sql.text)
            else:
                status = VerificationStatus.GRAMMAR_FAIL
        except Exception as e:
            logger.warning(f"Grammar verification errored, treating as pass: {e}")

    # --- Stage 2: Schema (table/column existence) ---
    if status == VerificationStatus.PASS and schema is not None and (vcfg is None or vcfg.schema_check):
        try:
            sv = SchemaVerifier(schema)
            schema_valid, schema_err = sv.verify(sql, ast)
            if not schema_valid:
                status = VerificationStatus.SCHEMA_FAIL
                error_message = schema_err
        except Exception as e:
            logger.warning(f"Schema verification errored, treating as pass: {e}")

    # --- Stage 3: Execution ---
    exec_enabled = vcfg is None or vcfg.execution_check_slm
    if status == VerificationStatus.PASS and exec_enabled and db_path and db_path != ":memory:":
        if candidate_exec is not None:
            execution_valid = candidate_exec.get("exec_ok", True)
            if not execution_valid:
                status = VerificationStatus.EXECUTION_FAIL
                error_message = candidate_exec.get("error")
            else:
                from generator.candidate_selector import flag_empty_for_repair

                if flag_empty_for_repair(
                    candidate_exec,
                    repair_on_empty=getattr(vcfg, "repair_on_empty", True) if vcfg else True,
                    generations=generation_count,
                    max_repairs=vcfg.max_repair_attempts if vcfg else 1,
                ):
                    execution_valid = False
                    status = VerificationStatus.EXECUTION_FAIL
                    error_message = "Query executed but returned an empty result set (0 rows)."
        else:
            try:
                ev = ExecutionVerifier(
                    schema, db_path,
                    sample_size=vcfg.sample_size if vcfg else 100,
                    timeout=vcfg.timeout_seconds if vcfg else 5,
                )
                execution_valid, exec_err, execution_result = ev.verify(sql)
                ev.close()
                if not execution_valid:
                    status = VerificationStatus.EXECUTION_FAIL
                    error_message = exec_err
            except Exception as e:
                logger.warning(f"Execution verification errored, treating as pass: {e}")

    vr = VerificationResult(
        status=status,
        grammar_valid=grammar_valid, schema_valid=schema_valid, execution_valid=execution_valid,
        error_message=error_message, structured_feedback=None, execution_result=execution_result,
    )
    if status != VerificationStatus.PASS:
        try:
            fb = FeedbackGenerator().generate(vr)
            if fb:
                vr.structured_feedback = {"feedback": fb}
        except Exception as e:
            logger.debug(f"Feedback generation failed: {e}")

    sql.verified = status == VerificationStatus.PASS
    sql.verification_result = vr
    return vr
